server:
   port: 8090


spring:
   datasource:
     db1:
       jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=CST
       username: root
       password: root

     db2:
       jdbc-url: jdbc:mysql://localhost:3306/shopping?serverTimezone=CST
       username: root
       password: root