server:
  port: 8090

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=CST
        username: root
        password: root


    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate.ddl-auto: update